config/routes.rb
require 'sidekiq/web'

CanaryClip::Application.routes.draw do
  root :to => 'marketing#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: "registrations" }

  namespace :user do
    resources :schematics, :path => :builds, only: [:index, :edit, :update, :destroy]
    resources :character_claims, only: [:index, :show, :new, :create]

    resources :characters, only: [] do
      member do
        post :switch
      end
    end

    resources :servers, only: [:index, :show, :new, :create, :edit, :update] do
      collection do
        get :download
      end
    end
  end

  namespace :plugin do
    resources :character_claims, only: [] do
      member do
        post :claim
      end
    end
    resources :schematics, only: [:create, :download] do
      member do
        get :download
      end
    end
  end

  get 'about', to: "documentation#about"
  get 'quick_start', to: "documentation#quick_start"
  get 'server_setup', to: "documentation#server_setup"
  get 'character_claims', to: "documentation#character_claims"

  resources :blocks, only: [:show]
  resources :characters, only: [:show]
  resources :servers, only: [:show]
  resources :tags, only: [:show]

  get '/schematics', to: redirect('/builds')
  get '/schematics/:id', to: redirect('/builds/%{id}')

  resources :schematics, :path => :builds, only: [:index, :show, :new, :create] do
    resources :favorites, only: [:create, :destroy]

    member do
      get :download
    end
  end

  get '/:id', to: redirect('/builds/%{id}')
end

app/controllers/marketing_controller.rb
class MarketingController < ApplicationController

  def index
    @marketing_render  = Render.high_resolution.order('random()').first
    @schematic         = Schematic.published.order('random()').first
    @server            = Server.official
    @anatomy_schematic = Schematic.find_by_permalink("xDlJWAV")
  end

end

app/views/marketing/index.html.haml
- content_for :head do
  :css
    #canvas-image {
      background-image: url(#{@marketing_render.file.url});
    }

.container-fluid
  .row
    #particles-js
      %canvas#canvas-image
    .canvas-overlay
      .top-bar
        .container
          .row
            .col-xs-12
              .pull-left
                = link_to root_url, class: 'site-logo-link' do
                  .title= image_tag('canary.png')
              .pull-right
                = render partial: "layouts/menu"
      .container
        .row.text-center.slogan-text
          .col-xs-12
            %h1 Share Minecraft Builds Online
            .lead Inspire Other Builders With Your Creations
          .col-xs-12.col-md-6.col-md-offset-3
            = link_to '#', class: 'btn btn-primary btn-lg btn-block start-magic' do
              = fa_icon('magic')
              = "Start The Magic"

%br
.container#getting-started
  .row
    .col-xs-12
    .col-xs-12.col-md-6
      %h2 Showcase Your Minecraft Builds
      %p
        %strong You built something awesome in Minecraft. Now share it with the world!
      %p CanaryClip is a platform to publish your Minecraft builds. Use it to share your builds with your friends, or get inspired by what others have built.
      %p Here are a few ideas to get you started...
      %ul
        %li Getting noticed in the Minecraft community is difficult! Share your Minecraft build on CanaryClip so others can find your work.
        %li Find inspiration for your next project. If you like a build, download it to use in your next build. After all, imitation is the highest form of flattery!
        %li Working on a large project with many builders? CanaryClip can help your team collaborate. Every builder can work on their part independently. Then bring all the pieces back together to build something amazing!
      - if current_character.blank?
        %p Ready now? First step, Claim your Minecraft Character!
        %br
        = link_to new_user_character_claim_path, class: 'btn btn-primary btn-lg btn-block' do
          = fa_icon 'sign-in'
          &nbsp;
          = "Claim Your Minecraft Character"
      - else
        %p Ready now? Next step, upload a Minecraft build!
        %br
        = link_to new_schematic_path, class: 'btn btn-primary btn-lg btn-block' do
          = fa_icon 'upload'
          &nbsp;
          = "Upload Minecraft Build"
      %br
      %br
    .col-xs-12.col-md-6
      .schematic-preview-card= link_to image_tag(@schematic.primary_render.file.url, class: 'img-responsive rounded'), schematic_path(@schematic)
      %br

.container-fluid.pagination-wrapper.schematic-stripe
  .row
    .col-xs-12.text-center
      %h2 Build Anatomy
      %br
      %br
      %br
  .row
    .col-xs-12.col-md-4.col-md-offset-5.col-sm-5.col-sm-offset-6
      = render partial: 'schematics/show', locals: {schematic: @anatomy_schematic, single_column: true}
  %br
  .row.visible-xs-inline-block
    .col-xs-12
      %br
      %ul
        %li= t('schematics.features.renders_html')
        %li= t('schematics.features.download_favorite_views_html')
        %li= t('schematics.features.description_and_tags_html')
        %li= t('schematics.features.blocks_html')

-# .white-background
-#   .container-fluid.squared-stripe
-#     .container
-#       .row
-#         .col-xs-12.col-md-6
-#           .embed-responsive.embed-responsive-16by9
-#             %iframe{class: "embed-responsive-item", width: "560", height: "315", src: "https://www.youtube.com/embed/FbE3eVabLX8", frameborder: "0", allowfullscreen: true}
-#           %br
-#           %br
-#         .col-xs-12.col-md-6
-#           %h2 CanaryClip Minecraft Mod
-#           %p= "The CanaryClip Minecraft Mod allows you to upload and download builds <strong><i>without</i></strong> leaving your Minecraft server. Follow these guides to get started!".html_safe
-#           %br
-#           = link_to quick_start_path, class: 'btn btn-primary btn-lg btn-block' do
-#             = fa_icon 'bolt'
-#             &nbsp;
-#             = "Player Quick Start Guide"
-#           %br
-#           = link_to server_setup_path, class: 'btn btn-primary btn-lg btn-block' do
-#             = fa_icon 'server'
-#             &nbsp;
-#             = "Add CanaryClip To Your Server"
-#           %br
-#           %br

- content_for :script do
  :javascript

    _.defer(function(){
      $('body').chardinJs('start');
    });

    var bounce = new Bounce();
      bounce
        .scale({
          from: { x: 0, y: 1 },
          to: { x: 1, y: 1 },
          easing: "bounce",
          duration: 1000,
          stiffness: 1
        })
        .scale({
          from: { x: 1, y: 0 },
          to: { x: 1, y: 1 },
          easing: "bounce",
          duration: 1000,
          stiffness: 1,
          bounces: 6
        });

    $(document).ready(function(){

      bounce.applyTo($('.start-magic'));

      $('.start-magic').on('click', function(){
        $.scrollTo($("#getting-started").offset().top-100, 350);

        return false;
      });

      var granimInstance = new Granim({
        element: '#canvas-image',
        direction: 'top-bottom',
        opacity: [1, .5, 0],
        isPausedWhenNotInView: true,
        states : {
            "default-state": {
                gradients: [
                    ['#485563', '#29323c', '#29323c'],
                    ['#00c6ff', '#0072ff', '#0072ff']
                ],
                transitionSpeed: 10000
            }
        }
      });
    });

    particlesJS("particles-js", {
      "particles": {
        "number": {
          "value": 80,
          "density": {
            "enable": true,
            "value_area": 800
          }
        },
        "color": {
          "value": "#ffffff"
        },
        "shape": {
          "type": "circle",
          "stroke": {
            "width": 0,
            "color": "#000000"
          },
          "polygon": {
            "nb_sides": 5
          },
          "image": {
            "src": "img/github.svg",
            "width": 100,
            "height": 100
          }
        },
        "opacity": {
          "value": 0.5,
          "random": false,
          "anim": {
            "enable": false,
            "speed": 1,
            "opacity_min": 0.1,
            "sync": false
          }
        },
        "size": {
          "value": 3,
          "random": true,
          "anim": {
            "enable": false,
            "speed": 40,
            "size_min": 0.1,
            "sync": false
          }
        },
        "line_linked": {
          "enable": true,
          "distance": 150,
          "color": "#ffffff",
          "opacity": 0.4,
          "width": 1
        },
        "move": {
          "enable": true,
          "speed": 6,
          "direction": "none",
          "random": false,
          "straight": false,
          "out_mode": "out",
          "bounce": false,
          "attract": {
            "enable": false,
            "rotateX": 600,
            "rotateY": 1200
          }
        }
      },
      "interactivity": {
        "detect_on": "canvas",
        "events": {
          "onhover": {
            "enable": false,
            "mode": "grab"
          },
          "onclick": {
            "enable": false,
            "mode": "push"
          },
          "resize": true
        },
        "modes": {
          "grab": {
            "distance": 140,
            "line_linked": {
              "opacity": 1
            }
          },
          "bubble": {
            "distance": 400,
            "size": 40,
            "duration": 2,
            "opacity": 8,
            "speed": 3
          },
          "repulse": {
            "distance": 200,
            "duration": 0.4
          },
          "push": {
            "particles_nb": 4
          },
          "remove": {
            "particles_nb": 2
          }
        }
      },
      "retina_detect": true
    });