config/routes.rb
require 'sidekiq/web'

CanaryClip::Application.routes.draw do
  root :to => 'marketing#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: "registrations" }

  namespace :user do
    resources :schematics, :path => :builds, only: [:index, :edit, :update, :destroy]
    resources :character_claims, only: [:index, :show, :new, :create]

    resources :characters, only: [] do
      member do
        post :switch
      end
    end

    resources :servers, only: [:index, :show, :new, :create, :edit, :update] do
      collection do
        get :download
      end
    end
  end

  namespace :plugin do
    resources :character_claims, only: [] do
      member do
        post :claim
      end
    end
    resources :schematics, only: [:create, :download] do
      member do
        get :download
      end
    end
  end

  get 'about', to: "documentation#about"
  get 'quick_start', to: "documentation#quick_start"
  get 'server_setup', to: "documentation#server_setup"
  get 'character_claims', to: "documentation#character_claims"

  resources :blocks, only: [:show]
  resources :characters, only: [:show]
  resources :servers, only: [:show]
  resources :tags, only: [:show]

  get '/schematics', to: redirect('/builds')
  get '/schematics/:id', to: redirect('/builds/%{id}')

  resources :schematics, :path => :builds, only: [:index, :show, :new, :create] do
    resources :favorites, only: [:create, :destroy]

    member do
      get :download
    end
  end

  get '/:id', to: redirect('/builds/%{id}')
end

app/models/schematic.rb
class Schematic < ActiveRecord::Base
  self.per_page = 15

  is_impressionable
  acts_as_taggable

  serialize :parsed_nbt_data, JSON

  belongs_to :character
  belongs_to :server
  belongs_to :texture_pack
  belongs_to :user

  has_many :block_counts, dependent: :destroy
  has_many :blocks, through: :block_counts

  has_many :favorites, dependent: :destroy
  has_many :favorited_by_characters, through: :favorites, source: :character

  has_many :tracked_downloads, dependent: :destroy
  has_many :downloaded_by_characters, through: :tracked_downloads, source: :character

  has_many :renders, -> { order(position: :asc) }, dependent: :destroy

  # Initially, this will be Standard Resolution with CameraAngle::PRIMARY
  # But users can change this by re-ordering
  has_one :primary_render,
    -> { where(position: 1) },
    class_name: "Render"

  accepts_nested_attributes_for :renders

  has_attached_file :file

  validates_attachment :file,
    :presence     => true,
    :size         => { in: 0..10.megabytes }

  # TODO: Why do we have to disable in initializers/paperclip.rb?
  validates_attachment_content_type :file, content_type: ['application/x-gzip', 'application/gzip', 'application/octet-stream']
  validates_attachment_file_name :file, :matches => [/schematic\Z/]

  validates :texture_pack, presence: true
  validates :permalink, uniqueness: true, allow_blank: true
  validate :character_or_user_required

  validates :width, :length, :height,
    numericality: {greater_than_or_equal_to: 0, only_integer: true},
    allow_blank: true

  scope :published, -> { where(state: :published) }
  scope :chronological, -> { order(:created_at) }

  attr_accessor :temporary_file, :character_username

  before_validation :set_default_texture_pack
  before_validation :set_character_from_character_username
  before_validation :set_user_from_character
  before_destroy :verify_destroyable
  after_create :delete_temporary_file
  after_create :set_permalink
  after_create :sync_permalink_to_file

  state_machine :state, :initial => :new do
    after_transition :new => :collecting_metadata,
      :do => :schedule_metadata_collection
    after_transition :collecting_metadata => :rendering,
      :do => :create_renders

    event :collect_metadata do
      transition :new => :collecting_metadata
    end

    event :render do
      transition :collecting_metadata => :rendering
    end

    event :publish do
      transition :rendering => :published
    end
  end

  def destroyable
    published?
  end
  alias :destroyable? :destroyable

  # Sanitize?
  def pipelined_description
    SocialPipeline.call(description.to_s)[:output].to_s
  end

  def admin_access?(user)
    user.schematics.where(id: self).exists?
  end

  def to_param
    permalink
  end

  def s3_file
    @temporary = Tempfile.new(UUID.generate)
    @temporary.binmode

    file.copy_to_local_file(:original, @temporary.path)

    begin
      yield(@temporary)
    ensure
      @temporary.close
      @temporary.unlink
    end
  end

  def region_paster
    @region_paster ||= RegionPaster.new(self)
  end
  delegate :paste_x, :paste_y, :paste_z, :paste_coordinates, to: :region_paster

  # Keep inspect sane by omitting parsed_nbt_data
  def inspect
    inspection = if @attributes
      self.class.column_names.collect { |name|
        if has_attribute?(name)
          if name == 'parsed_nbt_data'
            "#{name}: ..."
          else
            "#{name}: #{attribute_for_inspect(name)}"
          end
        end
      }.compact.join(", ")
    else
      "not initialized"
    end

    "#<#{self.class} #{inspection}>"
  end

  def raw_schematic_data=(data)
    filepath = "#{Rails.root}/tmp/schematics/#{object_id}-#{Time.now.to_i}.schematic"

    File.open(filepath, "w"){|file| file.write(data)}
    File.open(filepath, "r"){|file| self.file = file}

    self.temporary_file = filepath
  end

  def total_block_count
    block_counts.visible.sum(:count)
  end

  def total_show_impressions
    impressions.where(action_name: 'show').count
  end

  def total_download_impressions
    impressions.where(action_name: 'download').count
  end

  private

  def character_or_user_required
    if character.blank? && user.blank?
      errors.add(:base, "Character or user must be present")
    end
  end

  def set_default_texture_pack
    self.texture_pack ||= TexturePack.default
  end

  # This should realistically be an admin-only feature
  def set_character_from_character_username
    if character_username.present?
      self.user      = nil
      self.character = Character.find_or_create_by!(username: character_username)
    end
  end

  def set_user_from_character
    self.user ||= character.try(:user)
  end

  def verify_destroyable
    if !destroyable
      errors.add(:base, "cannot be destroyed")
      return false
    end
  end

  def delete_temporary_file
    if temporary_file.present?
      File.delete temporary_file
    end
  end

  # This has to be in an after_create since we need
  # an id to generate the hashid
  def set_permalink
    update_column :permalink, SCHEMATIC_HASHIDS.encode(id)
  end

  def sync_permalink_to_file
    update_column :file_file_name, "#{permalink}.schematic"
  end

  def schedule_metadata_collection
    Schematic::CollectMetadataWorker.perform_async(id)
  end

  def create_renders
    CameraAngle::AVAILABLE.each do |camera_angle|
      renders.create!(
        :schematic    => self,
        :camera_angle => camera_angle,
        :texture_pack => texture_pack
      )
    end

    renders.each(&:schedule!)
  end

end

app/controllers/plugin/schematics_controller.rb
class Plugin::SchematicsController < Plugin::BaseController
  before_filter :find_schematic, only: [:download]
  before_filter :log_impression, only: [:download]
  before_filter :track_downloads, only: [:download]

  def create
    @schematic = @server.schematics.new(create_params)
    @schematic.character = @character

    if @schematic.save
      @schematic.collect_metadata!

      render_plugin_text I18n.t('plugin.schematics.upload_success', permalink: @schematic.permalink)
    else
      render_plugin_text I18n.t('plugin.schematics.validation_error')
    end
  end

  def download
    send_file(Paperclip.io_adapters.for(@schematic.file).path, {
      :type        => @schematic.file_content_type,
      :disposition => "attachment",
      :filename    => @schematic.file_file_name
    })
  end

  private

  def create_params
    params.require(:schematic)
      .permit(:raw_schematic_data)
  end

  def find_schematic
    @schematic = Schematic.find_by_permalink(params[:id])

    if @schematic.blank?
      render_plugin_text I18n.t('plugin.schematics.not_found', permalink: params[:id])
    end
  end

  def log_impression
    impressionist(@schematic)
  end

  def track_downloads
    TrackedDownload.create!(
      :character => @character,
      :schematic => @schematic
    )
  end

end

app/controllers/schematics_controller.rb
class SchematicsController < ApplicationController
  load_and_authorize_resource find_by: :permalink

  before_filter :log_impression, only: [:show, :download]
  before_filter :track_downloads, only: [:download]

  def index
    @marketing_render = Render.high_resolution.order('random()').first
    @schematics       = Schematic.order("created_at desc").published.page(params[:page])
  end

  def show
    @favorite   = @schematic.favorites.for_character(current_character)
    @schematics = Schematic.order("random()").published.where.not(id: @schematic).limit(6)
  end

  def new
    @schematic = current_user.schematics.new
    @schematic.character = current_character
  end

  def create
    @schematic = current_user.schematics.new(create_params)
    @schematic.character = current_character

    if @schematic.save
      @schematic.collect_metadata!
      flash[:success] = "Your build was uploaded successfully! It will be published once rendered (approximately 5-10 minutes)."
      redirect_to edit_user_schematic_path(@schematic)
    else
      render action: :new
    end
  end

  def download
    send_file(Paperclip.io_adapters.for(@schematic.file).path, {
      :type        => @schematic.file_content_type,
      :disposition => "attachment",
      :filename    => @schematic.file_file_name
    })
  end

  private

  def log_impression
    impressionist(@schematic)
  end

  def track_downloads
    if current_character.present?
      TrackedDownload.create!(
        :character => current_character,
        :schematic => @schematic
      )
    end
  end

  def create_params
    permitted = [:file, :texture_pack_id]

    if current_user.try(:admin?)
      permitted.push(:character_username)
    end

    params.require(:schematic)
      .permit(permitted)
  end

end

app/controllers/user/schematics_controller.rb
class User::SchematicsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource find_by: :permalink

  def index
    @schematics = current_user.schematics.order("created_at desc").page(params[:page])
  end

  def edit
  end

  def update
    @schematic.attributes = update_params
    @schematic.save!

    redirect_to schematic_path(@schematic)
  end

  def destroy
    @schematic.destroy
    redirect_to schematics_path
  end

  private

  def update_params
    params.require(:schematic)
      .permit(:description, :tag_list, renders_attributes: [:id, :position])
  end

end

app/helpers/schematics_helper.rb
module SchematicsHelper

  def schematic_state_label_class(state)
    case state
    when 'new'
      'label-default'
    when 'collecting_metadata'
      'label-info'
    when 'rendering'
      'label-warning'
    when 'published'
      'label-primary'
    end
  end

  def schematic_state_description(state)
    case state
    when 'new'
      content_tag :div, class: "alert alert-warning" do
        "This build is currently waiting to be analyzed."
      end
    when 'collecting_metadata'
      content_tag :div, class: "alert alert-warning" do
        "This build is currently being analyzed before it can be rendered."
      end
    when 'rendering'
      content_tag :div, class: "alert alert-warning" do
        "This build is being rendered&hellip; Rendering usually takes 5-10 minutes.".html_safe
      end
    when 'published'
      content_tag :div, class: "alert alert-success" do
        "#{fa_icon('check-circle ')} This build has been published and is discoverable by other users.".html_safe
      end
    end
  end

end

app/views/schematics/_collection.html.haml
- if schematics.blank?
  .container
    .col-xs-12.text-center
      .giant-fa-icon= fa_icon 'terminal'
      .lead No Builds Found
      %p Get started by #{link_to('uploading your Minecraft build', new_schematic_path)}.
- else
  .container-fluid
    .grid
      - schematics.each do |schematic|
        .grid-item.col-xs-12.col-sm-6.col-lg-4
          .schematic-card.rounded
            = link_to image_tag(schematic.primary_render.file.url, class: 'img-responsive semi-gray-scale'), schematic_path(schematic)
            .card-info.light-background
              .row
                .col-xs-6
                  .roboto
                    = link_to schematic.permalink, schematic_path(schematic)
                .col-xs-6.text-right
                  = "#{fa_icon('download')} #{number_with_delimiter(schematic.total_download_impressions)}".html_safe
                  = "#{fa_icon('heart')} #{number_with_delimiter(schematic.favorited_by_characters.count)}".html_safe
              - if schematic.tags.present?
                %br
                - schematic.tags.each do |tag|
                  %span.tag.rounded
                    = link_to tag.name, tag_path(tag.name)
              .strike
                %span= "#{number_with_delimiter(schematic.total_block_count)} Blocks"
              - schematic.block_counts.visible.most_used_order.each do |block_count|
                = link_to block_icon_with_title(block_count), block_path(block_count.block)

-content_for :script do
  :javascript
    var $grid = $('.grid').masonry({
      // options...
    });
    // layout Masonry after each image loads
    $grid.imagesLoaded().progress( function() {
      $grid.masonry('layout');
    });

app/views/schematics/_show.html.haml
:ruby
  single_column     = local_assigns.fetch(:single_column, false)
  slide_show_medium = (single_column ? "col-md-12" : "col-md-8")
  menu_medium       = (single_column ? "col-md-12" : "col-md-4")

.row.schematic-view
  .col-xs-12.gradient-wrap.schematic-column{:class => slide_show_medium, 'data-match-height' => "schematic-column-group"}
    .slick-slider{"data-intro" => t('schematics.features.renders_html'), "data-position" => "left"}
      - schematic.renders.standard_resolution.completed.each_with_index do |render, index|
        = image_tag render.file.url, class: "semi-gray-scale rounded"
    %br
  .col-xs-12.schematic-sidebar.schematic-column.light-background.rounded{:class => menu_medium, 'data-match-height' => "schematic-column-group"}
    %h1.roboto
      = schematic.permalink
      .pull-right
        %ul.list-inline
          %li
            = link_to quick_start_path, title: "Learn how to use the short code" do
              = fa_icon('question-circle')
          - if can?(:edit, schematic)
            %li
              = link_to edit_user_schematic_path(schematic), title: "Edit Build" do
                = fa_icon 'cog'
    .strike
      %span= formatted_date schematic.created_at
    - if schematic.character.present?
      .row.character-with-possible-server-row
        .col-xs-12
          .pull-left
            = image_tag(schematic.character.avatar.url, class: 'two-row-character-avatar')
          .pull-left.character-and-server
            %span= link_to schematic.character, character_path(schematic.character)
            - if schematic.server.present?
              %p= link_to(schematic.server, server_path(schematic.server))
    %br
    .row{"data-intro" => t('schematics.features.download_favorite_views_html'), "data-position" => "left"}
      .col-xs-12
        .row
          .col-xs-12
            = link_to "#{fa_icon('download')} #{number_with_delimiter(schematic.total_download_impressions)}".html_safe, download_schematic_path(schematic), class: 'btn btn-primary', title: 'Download schematic file to your computer'
            - if @favorite.present?
              = link_to "#{fa_icon('heart')} #{number_with_delimiter(schematic.favorited_by_characters.count)}".html_safe, schematic_favorite_path(schematic, @favorite), class: 'btn btn-danger', method: :delete, title: 'Click to unfavorite'
            - else
              = link_to "#{fa_icon('heart-o')} #{number_with_delimiter(schematic.favorited_by_characters.count)}".html_safe, schematic_favorites_path(schematic), class: 'btn btn-danger', method: :post, title: 'Click to favorite'
            &nbsp;
            %span= "#{number_with_delimiter(schematic.total_show_impressions)} Views"
    %br
    .row.small
      .col-xs-12
        = dimensions(schematic)
    .row{"data-intro" => t('schematics.features.description_and_tags_html'), "data-position" => "left"}
      .col-xs-12
        .description
          - if schematic.description.present?
            %br
            %blockquote
              %small
                %p= simple_format schematic.pipelined_description
        - if schematic.tags.present?
          %br
          - schematic.tags.each do |tag|
            %span.tag.rounded
              = link_to tag.name, tag_path(tag.name)
    .strike
      %span= "#{number_with_delimiter(schematic.total_block_count)} Blocks"
    .row{"data-intro" => t('schematics.features.blocks_html'), "data-position" => "left"}
      .col-xs-12
        - schematic.block_counts.visible.most_used_order.each do |block_count|
          = link_to block_icon_with_title(block_count), block_path(block_count.block)
    %hr
      .text-center= social_share_button_tag t('.social_share_title', name: schematic.permalink)

- content_for :script do
  :javascript

    $(document).ready(function(){
      new Clipboard('.btn-clipboard');

      $('.schematic-column').matchHeight();

      $(".select-all-to-copy").on("click", function () {
        $(this).select();
      });

      $('.slick-slider').slick({
        dots: true,
        accessibility: true,
        autoplay: true,
        arrows: false
      });

      $('.description-text').readmore({
        collapsedHeight: 100
      });
    });

app/views/schematics/index.html.haml
= title "Discover Builds"
= render partial: 'schematics/collection', locals: {schematics: @schematics}

- if @schematics.total_pages > 1
  .container-fluid.pagination-wrapper
    .row
      .container
        .row
          .col-xs-12.text-center
            = will_paginate @schematics, renderer: BootstrapPagination::Rails

app/views/schematics/new.html.haml
= title "Upload Your Minecraft Build"

.container
  .row
    .col-xs-12.col-md-6.col-md-offset-3
      .well.well-lg.light-background
        %h1 Upload Minecraft Build

        %br
        %p
          Do you play single player Minecraft? You can get export your Minecraft build as a .schematic file using #{link_to('WorldEdit', 'https://wiki.sk89q.com/wiki/WorldEdit')} or #{link_to('MCEdit', 'http://www.mcedit.net/')}.
          %strong Or, if you're a Minecraft server admin, consider using the #{link_to('CanaryClip Minecraft Plugin', server_setup_path)}.

        %br
        = simple_form_for @schematic, url: "/builds" do |f|
          - if current_user.admin?
            = f.input :character_username, label: 'Minecraft Character Username', wrapper_html: {class: "no-margin"}
            %p.help-block
              %strong Admin Only:
              Clears user and associates to the Character with this username.
            %br
          = f.input :texture_pack_id, collection: TexturePack.all, include_blank: false
          = f.input :file, label: 'Minecraft Schematic File'
          %p.help-block Builds take 5-10 minutes once uploaded before they are published.
          %br
          = f.button :submit, value: "Upload Build", class: 'btn btn-primary btn-lg btn-block'

app/views/schematics/show.html.haml
= title "Build ##{@schematic.permalink}"

- content_for :head do
  %meta{name: "twitter:card", content: "summary_large_image"}
  %meta{name: "twitter:site", content: "@CanaryClip"}
  %meta{name: "twitter:url", content: schematic_url(@schematic)}
  %meta{name: "twitter:title", content: "Build ##{@schematic.permalink}"}
  %meta{name: "twitter:description", content: "Minecraft Build ##{@schematic.permalink} via CanaryClip. View and Download this build to your Minecraft world!"}
  %meta{name: "twitter:image", content: asset_url(@schematic.primary_render.file.url)}

  %meta{property: "og:url", content: schematic_url(@schematic)}
  %meta{property: "og:type", content: "website"}
  %meta{property: "og:title", content: "Build ##{@schematic.permalink}"}
  %meta{property: "og:image", content: asset_url(@schematic.primary_render.file.url)}
  %meta{property: "og:description", content: "Minecraft Build ##{@schematic.permalink} via CanaryClip. View and Download this build to your Minecraft world!"}
  %meta{property: "og:site_name", content: "CanaryClip"}
  %meta{property: "og:locale", content: "en_US"}

.container-fluid.schematic-stripe
  .row
    .container
      = render partial: 'schematics/show', locals: {schematic: @schematic}

.container-fluid.pagination-wrapper
  %br
  .row
    .container
      .row
        .col-xs-12.text-center
          %h5.uppercase Discover More Builds
  %br
  = render partial: 'schematics/collection', locals: {schematics: @schematics}