config/routes.rb
require 'sidekiq/web'

CanaryClip::Application.routes.draw do
  root :to => 'marketing#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: "registrations" }

  namespace :user do
    resources :schematics, :path => :builds, only: [:index, :edit, :update, :destroy]
    resources :character_claims, only: [:index, :show, :new, :create]

    resources :characters, only: [] do
      member do
        post :switch
      end
    end

    resources :servers, only: [:index, :show, :new, :create, :edit, :update] do
      collection do
        get :download
      end
    end
  end

  namespace :plugin do
    resources :character_claims, only: [] do
      member do
        post :claim
      end
    end
    resources :schematics, only: [:create, :download] do
      member do
        get :download
      end
    end
  end

  get 'about', to: "documentation#about"
  get 'quick_start', to: "documentation#quick_start"
  get 'server_setup', to: "documentation#server_setup"
  get 'character_claims', to: "documentation#character_claims"

  resources :blocks, only: [:show]
  resources :characters, only: [:show]
  resources :servers, only: [:show]
  resources :tags, only: [:show]

  get '/schematics', to: redirect('/builds')
  get '/schematics/:id', to: redirect('/builds/%{id}')

  resources :schematics, :path => :builds, only: [:index, :show, :new, :create] do
    resources :favorites, only: [:create, :destroy]

    member do
      get :download
    end
  end

  get '/:id', to: redirect('/builds/%{id}')
end

app/models/character_claim.rb
class CharacterClaim < ActiveRecord::Base
  belongs_to :character
  belongs_to :user

  validates :user, :character_username, :state, presence: true

  before_create :find_or_create_character
  after_create :set_token

  state_machine :state, :initial => :pending do
    after_transition :pending => :claimed,
      :do => :assign_character_to_user

    event :claim do
      transition :pending => :claimed
    end

    event :expire do
      transition :pending => :expired
    end
  end

  def to_param
    token
  end

  def claim_with_username_verification(username)
    if username == character_username
      claim!
    end
  end

  private

  def find_or_create_character
    self.character = Character.find_or_create_by!(username: character_username)
  end

  def set_token
    update_column :token, CHARACTER_CLAIM_HASHIDS.encode(id)
  end

  def assign_character_to_user
    user.characters << character

    if user.current_character.blank?
      user.update_column :current_character_id, character
    end

    CharacterClaimBuildMigrationWorker.perform_async(character.id)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :characters
  has_many :character_claims, inverse_of: :user
  has_many :owned_servers, foreign_key: :owner_user_id, class_name: "Server"

  has_many :schematics, dependent: :restrict_with_exception

  belongs_to :current_character, class_name: "Character"

  accepts_nested_attributes_for :character_claims
end

app/controllers/character_claims_controller.rb
class CharacterClaimsController < ApplicationController
  before_action :authenticate_user!

  def index
    @character_claims = current_user.character_claims
  end

  def show
    @character_claim = current_user.character_claims.find_by_token!(params[:id])
  end

  def new
    @character_claim = current_user.character_claims.new
  end

  def create
    @character_claim = current_user.character_claims.new
    @character_claim.attributes = create_params

    if @character_claim.save
      redirect_to character_claim_path @character_claim
    else
      render action: :new
    end
  end

  private

  def create_params
    params.require(:character_claim)
      .permit(:character_username)
  end
end

app/controllers/plugin/character_claims_controller.rb
class Plugin::CharacterClaimsController < Plugin::BaseController
  before_action :verify_server_allows_claims
  before_filter :find_character_claim

  def claim
    if @character_claim.claim_with_username_verification(@character.username)
      render_plugin_text I18n.t('plugin.character_claims.claimed', username: @character.username)
    else
      render_plugin_text I18n.t('plugin.character_claims.check_username', username: @character.username)
    end
  end

  private

  def find_character_claim
    @character_claim = CharacterClaim.find_by_token(params[:id])

    if @character_claim.blank?
      render_plugin_text I18n.t('plugin.character_claims.not_found')
    end
  end

  def verify_server_allows_claims
    if !@server.claims_allowed?
      render_plugin_text I18n.t('plugin.character_claims.claims_not_allowed')
    end
  end

end

app/controllers/user/character_claims_controller.rb
class User::CharacterClaimsController < ApplicationController
  before_action :authenticate_user!

  def index
    @character_claims = current_user.character_claims
  end

  def show
    @character_claim = current_user.character_claims.find_by_token!(params[:id])
    @server          = Server.official
  end

  def new
    @character_claim = current_user.character_claims.new
  end

  def create
    @character_claim = current_user.character_claims.new
    @character_claim.attributes = create_params

    if @character_claim.save
      redirect_to user_character_claim_path @character_claim
    else
      render action: :new
    end
  end

  private

  def create_params
    params.require(:character_claim)
      .permit(:character_username)
  end
end

app/controllers/user/characters_controller.rb
class User::CharactersController < ApplicationController
  before_action :authenticate_user!

  def switch
    @character = current_user.characters.find_by_permalink!(params[:id])

    current_user.current_character = @character
    current_user.save!

    redirect_to :back
  end

end

app/controllers/user/schematics_controller.rb
class User::SchematicsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource find_by: :permalink

  def index
    @schematics = current_user.schematics.order("created_at desc").page(params[:page])
  end

  def edit
  end

  def update
    @schematic.attributes = update_params
    @schematic.save!

    redirect_to schematic_path(@schematic)
  end

  def destroy
    @schematic.destroy
    redirect_to schematics_path
  end

  private

  def update_params
    params.require(:schematic)
      .permit(:description, :tag_list, renders_attributes: [:id, :position])
  end

end

app/controllers/user/servers_controller.rb
class User::ServersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource find_by: :permalink

  DOWNLOAD_PATH = "#{Rails.root}/private/worldedit-bukkit-6.1.4-canary_clip.jar"

  def index
    @servers = current_user.owned_servers
  end

  def show
  end

  def new
    @server = current_user.owned_servers.new
  end

  def create
    @server = current_user.owned_servers.new(create_params)

    if @server.save
      redirect_to user_server_path @server
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    @server.attributes = editable_params

    if @server.save
      redirect_to user_server_path @server
    else
      render action: :edit
    end
  end

  def download
    send_file DOWNLOAD_PATH
  end

  private

  def editable_params
    params.require(:server)
      .permit(:name, :hostname, :description)
  end

  def create_params
    params.require(:server)
      .permit(:name, :hostname, :description)
  end
end

app/helpers/character_claims_helper.rb
module CharacterClaimsHelper

  def character_claim_state_label_class(state)
    case state
    when 'pending'
      'label-warning'
    when 'claimed'
      'label-success'
    when 'expired'
      'label-danger'
    end
  end

end

app/views/user/character_claims/index.html.haml
= title "Manage Your Characters"

.container
  .row
    .col-xs-12.col-sm-3
      = render partial: "user/shared/menu"
    .col-xs-12.col-sm-9
      .well.well-lg.light-background
        .row
          .span.col-xs-12.col-md-6.text-center
            .giant-fa-icon= fa_icon "leaf"
            = link_to 'Character Claim Guide', character_claims_path
          .span.col-xs-12.col-md-6.text-center
            .giant-fa-icon= fa_icon "plus-square"
            = link_to t('.add_character_claim'), new_user_character_claim_path

        - if current_character.present?
          %br
          %br
          %h3 Currently, Known As&hellip;
          .well
            .row
              .span.col-xs-4
                = image_tag(current_character.avatar.url, class: "rounded img-responsive")
              .span.col-xs-8
                %h3= current_character.username
                %samp= current_character.uuid
                %br
                %br
                %p= "#{current_character.schematics.count} Builds, #{current_character.favorites.count} Favorites, #{current_character.tracked_downloads.count} Downloadeds"
          %p.help-block
            You're currently signed in as #{current_character.username}. That means you can manage builds owned by #{current_character.username}, and all interactions (such as downloads and favorites) on CanaryClip will be tracked back to #{current_character.username}.
            - if current_user.characters.count > 1
              %strong You can change the character you are known as below.

        - if current_user.characters.count > 1
          %br
          .strike
            %span #{current_user.characters.count} Characters
          %table.table.table-condensed.table-hover.table-striped.character-management-table
            %tbody
              - current_user.characters.each do |character|
                %tr{class: (current_character == character ? 'info' : '')}
                  %td.text-center
                    = image_tag(character.avatar.url, class: 'small-character-avatar')
                  %td
                    .lead.no-margin= link_to character.username, character_path(character)
                    %samp= character.uuid
                  %td.text-center
                    .switch-control
                      - if current_character == character
                        .picked-character= fa_icon "check-circle"
                      - else
                        = link_to switch_user_character_path(character), class: "btn btn-primary", method: :post, title: "Switch to #{character.username}" do
                          = fa_icon('sign-in')

app/views/user/character_claims/new.html.haml
= title t('.claim_your_character')

.container
  .row
    .col-xs-12.col-sm-3
      = render partial: "user/shared/menu"
    .col-xs-12.col-sm-9
      .well.well-lg.light-background
        %ol.breadcrumb
          %li= link_to "Characters", user_character_claims_path
          %li.active= t('.claim_your_character')

        - if current_character.blank?
          .alert.alert-warning{role: "alert"}
            %p
              = fa_icon "exclamation-triangle"
              %strong WARNING:
              You must claim your Minecraft character before you can participate on CanaryClip.

        %h1= t('.claim_your_character')
        %p= "Read the #{link_to('Character Claim Guide', character_claims_path)} for full instructions.".html_safe
        %br

        = simple_form_for [:user, @character_claim] do |f|
          = f.input :character_username
          = f.button :submit, value: "Claim your Character", class: 'btn btn-primary'

app/views/user/character_claims/show.html.haml
= title "Character Claim #{@character_claim.token}"

.container
  .row
    .col-xs-12.col-sm-3
      = render partial: "user/shared/menu"
    .col-xs-12.col-sm-9
      .well.well-lg.light-background
        %ol.breadcrumb
          %li= link_to "Characters", user_character_claims_path
          %li.active= "Character Claim #{@character_claim.token}"

        .row
          .col-xs-12
            %h2
              = image_tag(@character_claim.character.avatar.url, class: 'small-character-avatar')
              = @character_claim.character.username
              %span.label{class: character_claim_state_label_class(@character_claim.state)}
                = @character_claim.state
          .col-xs-12
            %br
            %label= CharacterClaim.human_attribute_name(:token)
            .input-group
              %input{type: 'text', readonly: 'readonly', id: 'server-authenticity-token-input', class: "form-control select-all-to-copy", value: @character_claim.token}
              %span.input-group-btn
                %button.btn.btn-secondary.btn-clipboard{type: "button", 'data-clipboard-target' => "#server-authenticity-token-input", title: 'Click to copy to clipboard'}= fa_icon('clipboard')
            %p.help-block
              = "Verify you own this character by connecting to server <samp>#{@server.hostname}</samp> in Minecraft. Once connected to the verification server, use the command <code>//can claim #{@character_claim.token}</code> to prove you own this character.".html_safe
            %p.help-block
              = "Verified Characters appear under #{link_to('Characters', user_character_claims_path)} settings.".html_safe

- content_for :script do
  :javascript
    $(document).ready(function(){
      new Clipboard('.btn-clipboard');

      $(".select-all-to-copy").on("click", function () {
        $(this).select();
      });
    });