config/routes.rb
require 'sidekiq/web'

CanaryClip::Application.routes.draw do
  root :to => 'marketing#index'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { registrations: "registrations" }

  namespace :user do
    resources :schematics, :path => :builds, only: [:index, :edit, :update, :destroy]
    resources :character_claims, only: [:index, :show, :new, :create]

    resources :characters, only: [] do
      member do
        post :switch
      end
    end

    resources :servers, only: [:index, :show, :new, :create, :edit, :update] do
      collection do
        get :download
      end
    end
  end

  namespace :plugin do
    resources :character_claims, only: [] do
      member do
        post :claim
      end
    end
    resources :schematics, only: [:create, :download] do
      member do
        get :download
      end
    end
  end

  get 'about', to: "documentation#about"
  get 'quick_start', to: "documentation#quick_start"
  get 'server_setup', to: "documentation#server_setup"
  get 'character_claims', to: "documentation#character_claims"

  resources :blocks, only: [:show]
  resources :characters, only: [:show]
  resources :servers, only: [:show]
  resources :tags, only: [:show]

  get '/schematics', to: redirect('/builds')
  get '/schematics/:id', to: redirect('/builds/%{id}')

  resources :schematics, :path => :builds, only: [:index, :show, :new, :create] do
    resources :favorites, only: [:create, :destroy]

    member do
      get :download
    end
  end

  get '/:id', to: redirect('/builds/%{id}')
end

app/models/server.rb
class Server < ActiveRecord::Base
  belongs_to :owner_user, class_name: "User"
  belongs_to :owner_character, class_name: "Character"

  has_many :schematics, dependent: :destroy

  validates_presence_of :name, :permalink,
    :owner_user, :authenticity_token, :hostname

  validates :name, :permalink, uniqueness: true

  validate :hostname_is_dns_hostname_or_ip_address
  validate :owner_character_must_belong_to_owner_user,
    if: Proc.new { |s| s.owner_character.present? }

  before_validation :set_permalink
  before_validation :set_authenticity_token, on: :create

  def self.official
    where(claims_allowed: true).first
  end

  def to_param
    permalink
  end

  def to_s
    name
  end

  private

  def set_permalink
    if name.present?
      self.permalink = name.parameterize
    end
  end

  def set_authenticity_token
    self.authenticity_token ||= UUID.generate(:compact)
  end

  def owner_character_must_belong_to_owner_user
    if !owner_user.characters.where(id: owner_character_id).exists?
      errors.add(:owner_character, :must_belong_to_user)
    end
  end

  def hostname_is_dns_hostname_or_ip_address
    any_ipv4 = Regexy::Web::IPv4.new(:normal) |
      Regexy::Web::IPv4.new(:with_port)

    if (hostname =~ any_ipv4).nil? && (hostname =~ Regexy::Web::HostName.new).nil?
      errors.add(:hostname, :invalid)
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :characters
  has_many :character_claims, inverse_of: :user
  has_many :owned_servers, foreign_key: :owner_user_id, class_name: "Server"

  has_many :schematics, dependent: :restrict_with_exception

  belongs_to :current_character, class_name: "Character"

  accepts_nested_attributes_for :character_claims
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController

  def show
    @server     = Server.find_by_permalink!(params[:id])
    @schematics = @server.schematics.order("created_at desc").published.page(params[:page])
  end

end

app/controllers/user/character_claims_controller.rb
class User::CharacterClaimsController < ApplicationController
  before_action :authenticate_user!

  def index
    @character_claims = current_user.character_claims
  end

  def show
    @character_claim = current_user.character_claims.find_by_token!(params[:id])
    @server          = Server.official
  end

  def new
    @character_claim = current_user.character_claims.new
  end

  def create
    @character_claim = current_user.character_claims.new
    @character_claim.attributes = create_params

    if @character_claim.save
      redirect_to user_character_claim_path @character_claim
    else
      render action: :new
    end
  end

  private

  def create_params
    params.require(:character_claim)
      .permit(:character_username)
  end
end

app/controllers/user/characters_controller.rb
class User::CharactersController < ApplicationController
  before_action :authenticate_user!

  def switch
    @character = current_user.characters.find_by_permalink!(params[:id])

    current_user.current_character = @character
    current_user.save!

    redirect_to :back
  end

end

app/controllers/user/schematics_controller.rb
class User::SchematicsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource find_by: :permalink

  def index
    @schematics = current_user.schematics.order("created_at desc").page(params[:page])
  end

  def edit
  end

  def update
    @schematic.attributes = update_params
    @schematic.save!

    redirect_to schematic_path(@schematic)
  end

  def destroy
    @schematic.destroy
    redirect_to schematics_path
  end

  private

  def update_params
    params.require(:schematic)
      .permit(:description, :tag_list, renders_attributes: [:id, :position])
  end

end

app/controllers/user/servers_controller.rb
class User::ServersController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource find_by: :permalink

  DOWNLOAD_PATH = "#{Rails.root}/private/worldedit-bukkit-6.1.4-canary_clip.jar"

  def index
    @servers = current_user.owned_servers
  end

  def show
  end

  def new
    @server = current_user.owned_servers.new
  end

  def create
    @server = current_user.owned_servers.new(create_params)

    if @server.save
      redirect_to user_server_path @server
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    @server.attributes = editable_params

    if @server.save
      redirect_to user_server_path @server
    else
      render action: :edit
    end
  end

  def download
    send_file DOWNLOAD_PATH
  end

  private

  def editable_params
    params.require(:server)
      .permit(:name, :hostname, :description)
  end

  def create_params
    params.require(:server)
      .permit(:name, :hostname, :description)
  end
end

app/views/user/servers/_form.html.haml
= simple_form_for [:user, server] do |f|
  = f.input :name
  = f.input :hostname
  = f.input :description
  = f.button :submit, 'Save', class: "btn btn-primary"

app/views/user/servers/edit.html.haml
= title "Edit #{@server.name}"

.container
  .row
    .col-xs-12.col-sm-3
      = render partial: "user/shared/menu"
    .col-xs-12.col-sm-9
      .well.well-lg.light-background
        %ol.breadcrumb
          %li= link_to "Servers", user_servers_path
          %li.active Edit #{@server.name}
        %h2 Edit #{@server.name}
        %p Read the #{link_to('Server Setup Guide', server_setup_path, target: '_blank')} for full instructions.
        %br
        = render partial: 'form', locals: {server: @server}

app/views/user/servers/index.html.haml
= title "Manage Your Minecraft Servers"

.container
  .row
    .col-xs-12.col-sm-3
      = render partial: "user/shared/menu"
    .col-xs-12.col-sm-9
      .well.well-lg.light-background

        .row
          .span.col-xs-12.col-md-4.text-center
            .giant-fa-icon= fa_icon "leaf"
            = link_to 'Server Setup Guide', server_setup_path
          .span.col-xs-12.col-md-4.text-center
            .giant-fa-icon= fa_icon "server"
            = link_to 'Add a Minecraft Server', new_user_server_path
          .span.col-xs-12.col-md-4.text-center
            .giant-fa-icon= fa_icon "download"
            = link_to 'Download CanaryClip Minecraft Plugin', download_user_servers_path

        - if @servers.present?
          %hr
          %table.table.table-condensed.table-hover.table-striped
            %tbody
              - @servers.each do |server|
                %tr
                  %td
                    .lead.no-margin= link_to server.name, user_server_path(server)
                    %samp= server.hostname
                  %td.text-center
                    = link_to 'Edit', edit_user_server_path(server)

app/views/user/servers/new.html.haml
= title "Join the CanaryClip Minecraft Server Network"

.container
  .row
    .col-xs-12.col-sm-3
      = render partial: "user/shared/menu"
    .col-xs-12.col-sm-9
      .well.well-lg.light-background
        %ol.breadcrumb
          %li= link_to "Servers", user_servers_path
          %li.active Join the CanaryClip Minecraft Server Network
        %h2 Join the CanaryClip Minecraft Server Network
        %p Read the #{link_to('Server Setup Guide', server_setup_path, target: '_blank')} for full instructions.
        %br
        = render partial: 'form', locals: {server: @server}

app/views/user/servers/show.html.haml
= title "#{@server.name}: #{@server.hostname}"

.container
  .row
    .col-xs-12.col-sm-3
      = render partial: "user/shared/menu"
    .col-xs-12.col-sm-9
      .well.well-lg.light-background
        %ol.breadcrumb
          %li= link_to "Servers", user_servers_path
          %li.active= @server.name
        %h2= @server.name
        %samp= @server.hostname
        %br
        %br
        %br
        %blockquote
          %p
            - if @server.description.present?
              = @server.description
            - else
              No description

        %br
        %label= Server.human_attribute_name(:authenticity_token)
        .input-group
          %input{type: 'text', readonly: 'readonly', id: 'server-authenticity-token-input', class: "form-control select-all-to-copy", value: @server.authenticity_token}
          %span.input-group-btn
            %button.btn.btn-secondary.btn-clipboard{type: "button", 'data-clipboard-target' => "#server-authenticity-token-input", title: 'Click to copy to clipboard'}= fa_icon('clipboard')
        %p.help-block= "This token is used to authenticate your server with CanaryClip when using the plugin. Without it, CanaryClip will not work properly. <strong>Treat your Authenticity Token as if it were a password. Do not reuse the Authenticity Token for more than one Minecraft server.</strong> If you have multiple Minecraft servers, simply register each one for a unique Authenticity Token.".html_safe

- content_for :script do
  :javascript
    $(document).ready(function(){
      new Clipboard('.btn-clipboard');

      $(".select-all-to-copy").on("click", function () {
        $(this).select();
      });
    });